### PR TITLE
Update translation.json

### PR DESCRIPTION
**Pull request by bnut96**
Anetts translation to Swedish

### CODE REVIEW

**Comment by anzioka** [comment]
It seems there is a problem with line 42 of the translation file. Please delete the quotation mark on line 42, then add a comma at the end of line 41.

**Comment by anzioka** [comment]
This line
 ```"adult_media": "Använde den vuxne en bärbar digital apparat (mobil, surfplatta, laptop) medan ditt barn skulle /aktivitet från Q6a/b/? Till exempel kanske en vuxen skickade ett sms mean barnet gjorde något annat i samma rum?",```

lacks an {{activity}} expression present in the English version:
```
"adult_media": "Was an adult using a mobile device (phone, tablet, laptop) while your child was {{activity}}?
For example, maybe a parent was sending text messages while your child did something else in the room."
```

Please fix.

**Comment by geekbeast** [comment]
For clarity on this, I think activity was translated to Swedish, but the tag has to stay in English. Will the rendered expression itself be translated?

**Comment by bnut96** [comment]
Yes, Sorry ! I just translated a little bit too much. It should be as
below. Should I change that or do you?

"adult_media": "Använde den vuxne en bärbar digital apparat (mobil,
surfplatta, laptop) medan ditt barn skulle {{activity}}? Till exempel
kanske en vuxen skickade ett sms mean barnet gjorde något annat i samma
rum?",

Den fre 16 apr. 2021 kl 06:09 skrev Alfonce Nzioka ***@***.***

**Comment by bnut96** [comment]
Sorry -  by mistake, I translated just a little bit too much.  We should
not translate the rendered expression - if you by that mean what is between
the double brackets.
Sorry!



Den fre 16 apr. 2021 kl 23:02 skrev Matthew Tamayo-Rios <
***@***.***>:

**Comment by anzioka** [comment]
Hi @bnut96, please provide the correct translation by updating this file https://github.com/bnut96/chronicle-web/blob/patch-1/src/core/i18n/sv/translation.json and commit your changes directly to the current branch (patch-1)

**Comment by anzioka** [comment]
> For clarity on this, I think activity was translated to Swedish, but the tag has to stay in English. Will the rendered expression itself be translated?

Yes @geekbeast the rendered expression will be translated correctly.

**Review by UnsungHero97 — APPROVED** [review]

**Review by anzioka — APPROVED** [review]

**Pull request merged**
